FROM registry.access.redhat.com/ubi9-minimal:latest

LABEL maintainer="pvn@novarese.net"
LABEL name="2022-08-enterprise-demo-drift-baseline"
LABEL org.opencontainers.image.title="2022-08-enterprise-demo-drift-baseline"
LABEL org.opencontainers.image.description="Simple image to test various policy rules with Anchore Enterprise."

HEALTHCHECK --timeout=10s CMD /bin/true || exit 1

RUN set -ex && \
    microdnf -y install ruby nodejs shadow-utils && \
    gem install ftpd:0.2.1 && \
    npm install -g --cache /tmp/empty-cache xmldom@0.4.0 && \
    npm cache clean --force && \
    microdnf -y clean all && \
    rm -rf /var/cache/yum /tmp 

## just to make sure we have a unique build each time
RUN date > /image_build_timestamp && \
    touch image_build_timestamp_$(date +%Y-%m-%d_%T)
    
USER nobody
ENTRYPOINT /bin/false
